# Generated by Django 5.2.8 on 2025-11-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomination',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
