# Generated by Django 5.2.8 on 2025-11-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_adminsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
