# Generated by Django 5.2.8 on 2025-11-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_candidate_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_portrait_url',
            field=models.URLField(blank=True),
        ),
    ]
