# Generated by Django 5.2.8 on 2025-11-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_candidate_photo_portrait_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo_portrait_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='pin',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
