# Generated by Django 5.2.8 on 2025-11-29 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_alter_candidate_photo_portrait_url_alter_voter_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('track', models.CharField(blank=True, help_text='For Grade 11–12, e.g. STEM, ABM. Leave blank for 7–10.', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='precinct',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='precinct',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='elections.gradelevel')),
            ],
            options={
                'ordering': ['grade_level__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='voter',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='elections.section'),
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Precinct',
        ),
    ]
