# Generated by Django 5.2.8 on 2025-11-30 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_gradelevel_remove_precinct_municipality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='elections.election')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations_made', to='elections.voter')),
                ('nominee_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_received', to='elections.section')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='elections.position')),
            ],
            options={
                'ordering': ['position__name', 'nominee_name'],
                'unique_together': {('election', 'position', 'nominator')},
            },
        ),
    ]
